name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true

      - name: Build Binaries
        run: |
          VERSION=$(git describe --tags --always --dirty)
          LDFLAGS="-X main.version=${VERSION}"
          
          # Build for each OS/arch combination
          GOOS=linux GOARCH=amd64 go build -ldflags "${LDFLAGS}" -o ru_linux_amd64 ./cmd/ru
          GOOS=linux GOARCH=arm64 go build -ldflags "${LDFLAGS}" -o ru_linux_arm64 ./cmd/ru
          GOOS=darwin GOARCH=amd64 go build -ldflags "${LDFLAGS}" -o ru_darwin_amd64 ./cmd/ru
          GOOS=darwin GOARCH=arm64 go build -ldflags "${LDFLAGS}" -o ru_darwin_arm64 ./cmd/ru
          GOOS=windows GOARCH=amd64 go build -ldflags "${LDFLAGS}" -o ru_windows_amd64.exe ./cmd/ru

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ru_linux_amd64
            ru_linux_arm64
            ru_darwin_amd64
            ru_darwin_arm64
            ru_windows_amd64.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 